In [1]:
import librosa as rs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import glob

from sklearn.model_selection import train_test_split

In [5]:
signal_index = list(range(33,67))
files = ['./F'+str(i)+'_loop.wav' for i in signal_index]
files

['./F33_loop.wav',
 './F34_loop.wav',
 './F35_loop.wav',
 './F36_loop.wav',
 './F37_loop.wav',
 './F38_loop.wav',
 './F39_loop.wav',
 './F40_loop.wav',
 './F41_loop.wav',
 './F42_loop.wav',
 './F43_loop.wav',
 './F44_loop.wav',
 './F45_loop.wav',
 './F46_loop.wav',
 './F47_loop.wav',
 './F48_loop.wav',
 './F49_loop.wav',
 './F50_loop.wav',
 './F51_loop.wav',
 './F52_loop.wav',
 './F53_loop.wav',
 './F54_loop.wav',
 './F55_loop.wav',
 './F56_loop.wav',
 './F57_loop.wav',
 './F58_loop.wav',
 './F59_loop.wav',
 './F60_loop.wav',
 './F61_loop.wav',
 './F62_loop.wav',
 './F63_loop.wav',
 './F64_loop.wav',
 './F65_loop.wav',
 './F66_loop.wav']

In [90]:
df_features = pd.DataFrame(columns = ['mean_amplitude', 'rms', 'pulse_count', 'zero_count',
       'mean_onset_strength', 'spectral_centroid'])
df_features['id'] = signal_index

In [91]:
df_features

,mean_amplitude,rms,pulse_count,zero_count,mean_onset_strength,spectral_centroid,id
0,NaN,NaN,NaN,NaN,NaN,NaN,33
1,NaN,NaN,NaN,NaN,NaN,NaN,34
2,NaN,NaN,NaN,NaN,NaN,NaN,35
3,NaN,NaN,NaN,NaN,NaN,NaN,36
4,NaN,NaN,NaN,NaN,NaN,NaN,37
5,NaN,NaN,NaN,NaN,NaN,NaN,38
6,NaN,NaN,NaN,NaN,NaN,NaN,39
7,NaN,NaN,NaN,NaN,NaN,NaN,40
8,NaN,NaN,NaN,NaN,NaN,NaN,41
9,NaN,NaN,NaN,NaN,NaN,NaN,42
10,NaN,NaN,NaN,NaN,NaN,NaN,43
11,NaN,NaN,NaN,NaN,NaN,NaN,44
12,NaN,NaN,NaN,NaN,NaN,NaN,45
13,NaN,NaN,NaN,NaN,NaN,NaN,46
14,NaN,NaN,NaN,NaN,NaN,NaN,47
15,NaN,NaN,NaN,NaN,NaN,NaN,48
16,NaN,NaN,NaN,NaN,NaN,NaN,49
17,NaN,NaN,NaN,NaN,NaN,NaN,50
18,NaN,NaN,NaN,NaN,NaN,NaN,51
19,NaN,NaN,NaN,NaN,NaN,NaN,52
20,NaN,NaN,NaN,NaN,NaN,NaN,53
21,NaN,NaN,NaN,NaN,NaN,NaN,54
22,NaN,NaN,NaN,NaN,NaN,NaN,55
23,NaN,NaN,NaN,NaN,NaN,NaN,56
24,NaN,NaN,NaN,NaN,NaN,NaN,57
25,NaN,NaN,NaN,NaN,NaN,NaN,58
26,NaN,NaN,NaN,NaN,NaN,NaN,59
27,NaN,NaN,NaN,NaN,NaN,NaN,60
28,NaN,NaN,NaN,NaN,NaN,NaN,61
29,NaN,NaN,NaN,NaN,NaN,NaN,62
30,NaN,NaN,NaN,NaN,NaN,NaN,63
31,NaN,NaN,NaN,NaN,NaN,NaN,64
32,NaN,NaN,NaN,NaN,NaN,NaN,65
33,NaN,NaN,NaN,NaN,NaN,NaN,66

In [43]:
# def consecutive(data, stepsize=1):
#     return np.split(data, np.where(np.diff(data) != stepsize)[0]+1)
# pulse_width = []
# a = np.array([0, 47, 48, 49, 50, 97, 98, 99])
# c = consecutive(np.flatnonzero(pulse))

# for p in c:
#     pulse_width.append(len(p))

# np.std(pulse_width)

0.49188015623720194

In [66]:
# y, sr = rs.load("F1_loop.wav")

# onset_env = rs.onset.onset_strength(y=y, sr=sr)
# tempo = rs.feature.tempo(onset_envelope=onset_env, sr=sr)
# pulse = rs.beat.plp(onset_envelope=onset_env, sr=sr)
# pulse

# beats_plp = np.flatnonzero(rs.util.localmax(pulse))

# z = rs.zero_crossings(y)
# np.nonzero(z)[0].size

76313

In [103]:
features = ['mean_amplitude', 'rms', 'pulse_count', 'zero_count',
       'mean_onset_strength', 'spectral_centroid']

mean_amplitude = []
rms = []
pulse_count = []
std_pulse_dist = []
zero_count = []
mean_onset_strength = []
spectral_centroid = []

feature_lists = [mean_amplitude, rms, pulse_count, zero_count, mean_onset_strength, spectral_centroid]


for f in files:
    y, sr = rs.load(f)

    onset_env = rs.onset.onset_strength(y=y, sr=sr)
    pulse = rs.beat.plp(onset_envelope=onset_env, sr=sr)
    beats_plp = np.flatnonzero(rs.util.localmax(pulse))
    z = rs.zero_crossings(y)
    cent = rs.feature.spectral_centroid(y=y, sr=sr)
    
    mean_amplitude.append(y.mean())
    rms.append(rs.feature.rms(y=y).mean())
    pulse_count.append(len(beats_plp))
    zero_count.append(np.nonzero(z)[0].size)    
    mean_onset_strength.append(onset_env.mean())
    spectral_centroid.append(cent.mean())

In [104]:
for i, f in enumerate(features):
    df_features[f] = feature_lists[i]

In [105]:
df_features

,mean_amplitude,rms,pulse_count,zero_count,mean_onset_strength,spectral_centroid,id
0,58.755852,9345.906250,27,84732,3.976186,1369.539155,33
1,-13.666315,4915.631836,40,6020,1.643997,298.526627,34
2,-4.330323,10885.784180,10,9399,1.501435,377.688809,35
3,-0.311235,1239.929199,29,54952,4.435668,2761.479328,36
4,13.209437,17916.542969,41,2132,1.410986,188.374538,37
5,99.270157,17951.806641,41,2332,1.847105,248.688896,38
6,-0.051913,11989.837891,7,2000,0.212024,243.247286,39
7,-25.021517,8149.632324,49,20731,2.013137,734.693451,40
8,4452.550293,8858.231445,44,128118,2.343372,2789.983532,41
9,24.677820,5539.378906,21,9411,1.442384,554.595841,42
10,-0.166309,4660.953613,48,129024,7.525324,972.170789,43
11,2.527575,877.464478,22,118814,1.242142,4873.887325,44
12,31.602543,15836.122070,7,1756,3.273740,207.872258,45
13,96.515762,19779.626953,41,2742,2.106161,313.519884,46
14,-0.068743,972.877014,29,156623,1.843988,6090.749089,47
15,-72.050896,6651.378906,25,124419,3.131563,3700.132082,48
16,85.033340,5333.061523,41,128831,1.861740,4885.220668,49
17,89.388229,17952.273438,37,40882,0.697107,1574.646354,50
18,14.983403,19097.322266,29,13695,1.702829,266.558924,51
19,194.032837,18569.082031,12,39466,1.055254,1175.423713,52
20,12.322424,20241.568359,29,13482,1.755787,280.761881,53
21,59.391811,9578.800781,16,8485,1.187953,319.625951,54
22,41.869347,12067.198242,19,90531,2.033880,3121.790523,55
23,85.191246,7534.145020,38,15324,1.856107,363.705189,56
24,324.059540,5521.005371,46,135761,3.672628,1857.193443,57
25,13.058780,19035.380859,38,55739,3.322459,388.839657,58
26,178.318192,12188.018555,19,11261,2.698395,254.285235,59
27,20.585594,18250.859375,30,30730,1.654344,898.134090,60
28,10.774463,20313.757812,30,13557,2.119050,366.049822,61
29,19.545633,3374.275635,16,8058,1.199713,344.763436,62
30,58.121227,6228.495117,16,8264,1.558967,360.331244,63
31,59.389534,9360.295898,17,8386,0.831940,307.941972,64
32,10.273185,4725.255859,33,115187,2.314902,4078.966997,65
33,-1.325145,5447.679688,26,6664,0.560019,313.325817,66

In [115]:
np.random.seed(42)
# rd32 = np.random.choice(range(35), size=32, replace=False)
# rd32.sort()
# rd32
df = df_features[(df_features.id !=47) &(df_features.id !=61)]
df

,mean_amplitude,rms,pulse_count,zero_count,mean_onset_strength,spectral_centroid,id
0,58.755852,9345.906250,27,84732,3.976186,1369.539155,33
1,-13.666315,4915.631836,40,6020,1.643997,298.526627,34
2,-4.330323,10885.784180,10,9399,1.501435,377.688809,35
3,-0.311235,1239.929199,29,54952,4.435668,2761.479328,36
4,13.209437,17916.542969,41,2132,1.410986,188.374538,37
5,99.270157,17951.806641,41,2332,1.847105,248.688896,38
6,-0.051913,11989.837891,7,2000,0.212024,243.247286,39
7,-25.021517,8149.632324,49,20731,2.013137,734.693451,40
8,4452.550293,8858.231445,44,128118,2.343372,2789.983532,41
9,24.677820,5539.378906,21,9411,1.442384,554.595841,42
10,-0.166309,4660.953613,48,129024,7.525324,972.170789,43
11,2.527575,877.464478,22,118814,1.242142,4873.887325,44
12,31.602543,15836.122070,7,1756,3.273740,207.872258,45
13,96.515762,19779.626953,41,2742,2.106161,313.519884,46
15,-72.050896,6651.378906,25,124419,3.131563,3700.132082,48
16,85.033340,5333.061523,41,128831,1.861740,4885.220668,49
17,89.388229,17952.273438,37,40882,0.697107,1574.646354,50
18,14.983403,19097.322266,29,13695,1.702829,266.558924,51
19,194.032837,18569.082031,12,39466,1.055254,1175.423713,52
20,12.322424,20241.568359,29,13482,1.755787,280.761881,53
21,59.391811,9578.800781,16,8485,1.187953,319.625951,54
22,41.869347,12067.198242,19,90531,2.033880,3121.790523,55
23,85.191246,7534.145020,38,15324,1.856107,363.705189,56
24,324.059540,5521.005371,46,135761,3.672628,1857.193443,57
25,13.058780,19035.380859,38,55739,3.322459,388.839657,58
26,178.318192,12188.018555,19,11261,2.698395,254.285235,59
27,20.585594,18250.859375,30,30730,1.654344,898.134090,60
29,19.545633,3374.275635,16,8058,1.199713,344.763436,62
30,58.121227,6228.495117,16,8264,1.558967,360.331244,63
31,59.389534,9360.295898,17,8386,0.831940,307.941972,64
32,10.273185,4725.255859,33,115187,2.314902,4078.966997,65
33,-1.325145,5447.679688,26,6664,0.560019,313.325817,66

In [117]:
y = np.zeros([32,1])
ids = np.random.choice(range(32), size=16, replace=False)
y[ids] = 1

# Assume X and y are your features and labels
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.5, random_state = 42)

In [119]:
np3_id = np.array(X_train.id)
np3_id.sort()
np3_id

array([34, 35, 36, 39, 40, 43, 48, 52, 53, 54, 55, 56, 60, 62, 63, 66],
      dtype=int64)

In [120]:
np4_id = np.array(X_test.id)
np4_id.sort()
np4_id

array([33, 37, 38, 41, 42, 44, 45, 46, 49, 50, 51, 57, 58, 59, 64, 65],
      dtype=int64)